---
- name: Play to Install Webserver
  hosts: all
  remote_user: root
  become: yes
  ignore_errors: yes

  tasks:
    - name: Install httpd package
      yum:
        name: httpd
        state: latest

    - name: start and enable httpd service
      service:
        name: httpd
        state: started
        enabled: yes
